### ISSUE TITLE
Tagging PAX in edit-mode doesn't work.

### ISSUE THREAD

**Issue by danielfenske** [evanpetzoldt/slackblast#13]
If a PAX is originally tagged in the post (e.g. @Abacus), the originally submission will correctly tag the account. However, if the backblast is edited in any way, the tag is replaced with a serialized string of numbers/characters (e.g. U04H66F4Y3C).

🚨 Note that this can be resolved by editing the backblast a third time and re-tagging the PAX originally tagged, but obviously this isn't ideal.

As an aside, really pleased with this major update to the /backblast tool! Great work on this 💪 The F3 Twin Cities is ecstatic about this new feature.

**Comment by evanpetzoldt** [comment]
Ahh, good catch! That shouldn't be too hard to fix
