### ISSUE TITLE
Unable to Copy Backblast anymore

### ISSUE THREAD

**Issue by scooterzp** [evanpetzoldt/slackblast#21]
The New version prevents backblasts from copy ability.  I have some folks that like to take from other backblasts.  Now it just comes up with the text "content_from_slackblast" instead of the actual text

**Comment by evanpetzoldt** [comment]
Closing this, as I've partially fixed this (copying now at least copies the moleskine text). To be truthful, part of my philosophy behind this design is to encourage regions to get away from the copy-paste method on backblasts, which often leads to data entry issues.
