### ISSUE TITLE
Automatically calculate count

### ISSUE THREAD

**Issue by agrigg** [evanpetzoldt/slackblast#34]
I created my own fork of the original Slackblast and one of the things that has kept me from switching over to this one is that I implemented the ability to automatically calculate the count. If we have a place to enter PAX in slack, PAX not in slack and FNGs then we can just calculate the count and not make people enter it. 

If that is of interest let me know and I can create a PR.

**Comment by evanpetzoldt** [comment]
@agrigg thanks for the offer, but a few weeks ago I already implemented an automatic count! PAX count is now an optional field, and will default to its internal calc if left blank, like you suggest. I'll go ahead and close this if that's alright

**Comment by agrigg** [comment]
Nice, that's great! You've been knocking out features left and right. Is there a note in the UI that it is calculated automatically if left blank?

**Comment by evanpetzoldt** [comment]
Yep! I left a little context blurb about it

**Comment by evanpetzoldt** [comment]
Let me add you to our dev community slack space, since you're working on slackblast as well

**Comment by agrigg** [comment]
Awesome, sounds great!
